/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class team_ictdb_mostdb_insert_Buffer_AsyncFlush */

#ifndef _Included_team_ictdb_mostdb_insert_Buffer_AsyncFlush
#define _Included_team_ictdb_mostdb_insert_Buffer_AsyncFlush
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     team_ictdb_mostdb_insert_Buffer_AsyncFlush
 * Method:    most
 * Signature: (JIZFJJI)V
 */
JNIEXPORT void JNICALL Java_team_ictdb_mostdb_insert_Buffer_00024AsyncFlush_most
  (JNIEnv *, jobject, jlong, jint, jboolean, jfloat, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
