/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class team_ictdb_mostdb_query_DualModeFilter */

#ifndef _Included_team_ictdb_mostdb_query_DualModeFilter
#define _Included_team_ictdb_mostdb_query_DualModeFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     team_ictdb_mostdb_query_DualModeFilter
 * Method:    createNativeOperator
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_team_ictdb_mostdb_query_DualModeFilter_createNativeOperator
  (JNIEnv *, jobject, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
